# Builds Roshan-Setup-<version>.exe from an already built release binary.
#
#   cargo build --release
#   pwsh packaging/windows/build-installer.ps1 -Version 1.2.3
#
# Needs Inno Setup 6 (https://jrsoftware.org/isinfo.php); ISCC.exe is found on
# PATH or in its default install folders.
param(
    [Parameter(Mandatory = $true)][string]$Version,
    # Folder with roshan.exe, e.g. target\release or target\<triple>\release.
    [string]$ReleaseDir = "target\release",
    [string]$OutDir = "dist"
)
$ErrorActionPreference = "Stop"
$root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
Set-Location $root

$exe = Join-Path $ReleaseDir "roshan.exe"
if (-not (Test-Path $exe)) { throw "No $exe; run cargo build --release first." }

# The icon and wizard pictures are generated by crates/roshan/build.rs.
$art = Get-ChildItem (Join-Path $ReleaseDir "build\roshan-*\out\roshan.ico") |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
if (-not $art) { throw "No generated roshan.ico under $ReleaseDir\build." }
$artDir = $art.DirectoryName

$iscc = @(
    (Get-Command ISCC.exe -ErrorAction SilentlyContinue).Source,
    "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe"
) | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
if (-not $iscc) { throw "Inno Setup 6 (ISCC.exe) was not found." }

New-Item -ItemType Directory -Force $OutDir | Out-Null
& $iscc /Q "/DAppVersion=$Version" "/DSourceExe=$(Resolve-Path $exe)" `
    "/DIconFile=$($art.FullName)" "/DArtDir=$artDir" "/O$(Resolve-Path $OutDir)" `
    packaging\windows\roshan.iss
if ($LASTEXITCODE -ne 0) { throw "ISCC failed with exit code $LASTEXITCODE" }
Get-Item (Join-Path $OutDir "Roshan-Setup-$Version.exe")
