; Inno Setup script for Roshan's Windows installer.
;
; Build (the Release workflow does this):
;   ISCC.exe /DAppVersion=1.2.3 /DSourceExe=path\to\roshan.exe ^
;            /DIconFile=path\to\roshan.ico /Odist packaging\windows\roshan.iss
;
; Installs per user into %LOCALAPPDATA%\Programs\Roshan with no admin prompt,
; so Roshan's updater can run the next installer silently.

#ifndef AppVersion
  #error Pass /DAppVersion=<version>
#endif
#ifndef SourceExe
  #error Pass /DSourceExe=<path to roshan.exe>
#endif

[Setup]
; Never change AppId: it ties updates and the uninstaller together.
AppId={{6E2C8C9A-4F7B-4E8E-9B1F-5A3D2C7E0B41}
AppName=Roshan
AppVersion={#AppVersion}
AppVerName=Roshan {#AppVersion}
AppPublisher=Roshan contributors
AppPublisherURL=https://github.com/sajjadmrx/roshan
AppSupportURL=https://github.com/sajjadmrx/roshan/issues
AppUpdatesURL=https://github.com/sajjadmrx/roshan/releases
VersionInfoVersion={#AppVersion}
; Per-user install: {autopf} is %LOCALAPPDATA%\Programs without admin rights.
PrivilegesRequired=lowest
DefaultDirName={autopf}\Roshan
DisableProgramGroupPage=yes
DisableReadyPage=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0
WizardStyle=modern
#ifdef IconFile
SetupIconFile={#IconFile}
#endif
; Logo artwork generated by crates/roshan/build.rs (OUT_DIR).
#ifdef ArtDir
WizardSmallImageFile={#ArtDir}\wizard-small.bmp
WizardImageFile={#ArtDir}\wizard-large.bmp
#endif
UninstallDisplayIcon={app}\roshan.exe
UninstallDisplayName=Roshan
OutputBaseFilename=Roshan-Setup-{#AppVersion}
Compression=lzma2/max
SolidCompression=yes
; Close a running Roshan before replacing it (also during silent updates).
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nRoshan opens the apps and commands you use every day, in the right order, with one click. It installs just for you and needs no administrator rights.

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Shortcuts:"; Flags: unchecked

[Files]
Source: "{#SourceExe}"; DestDir: "{app}"; DestName: "roshan.exe"; Flags: ignoreversion
Source: "..\..\LICENSE"; DestDir: "{app}"; DestName: "LICENSE.txt"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\Roshan"; Filename: "{app}\roshan.exe"
Name: "{autodesktop}\Roshan"; Filename: "{app}\roshan.exe"; Tasks: desktopicon

[Registry]
; Created by Roshan itself when "Open when you sign in" is on; only removed
; here, on uninstall (ValueType: none never creates anything).
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: none; ValueName: "Roshan"; Flags: uninsdeletevalue
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run"; ValueType: none; ValueName: "Roshan"; Flags: uninsdeletevalue

[Run]
; Normal install: offer to open Roshan on the last page.
Filename: "{app}\roshan.exe"; Description: "Open Roshan"; Flags: nowait postinstall skipifsilent
; An update started by Roshan (silent, with /RELAUNCH=1): reopen it right away.
Filename: "{app}\roshan.exe"; Parameters: "--updated"; Flags: nowait; Check: RelaunchAfterUpdate

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\Roshan\icons"
Type: filesandordirs; Name: "{localappdata}\Roshan\updates"

[Code]
// Roshan's updater runs this installer with /VERYSILENT /RELAUNCH=1. Other
// silent installs (e.g. by an administrator) do not start the app.
function RelaunchAfterUpdate: Boolean;
begin
  Result := WizardSilent and (ExpandConstant('{param:RELAUNCH|0}') = '1');
end;

// Sessions are the user's own work: keep them unless the user says otherwise.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{userappdata}\Roshan');
    if DirExists(DataDir) and not UninstallSilent then
      if MsgBox('Do you also want to delete your Roshan sessions and settings?' + #13#10 + #13#10 +
                'Choose No to keep them for next time.' + #13#10 + DataDir,
                mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
        DelTree(DataDir, True, True, True);
  end;
end;
